### ISSUE TITLE
Math formula on the documentation page does not display properly

### ISSUE THREAD

**Issue by ifengfan** [Climdyn/qgs#12]
Hi, Jonathan
I'm using the newest version of Chrome and have the [MathJax Plugin for Github](https://chrome.google.com/webstore/detail/mathjax-plugin-for-github/ioemnmodlmafdkllaclgeombjnmnbima?hl=zh) plugin loaded, but the Latex formula on the documentation pages still can not display properly. Could you tell me how to fix it? Thanks a lot.
![截屏2021-09-25 下午12 59 40](https://user-images.githubusercontent.com/7402999/134771029-6ed55b38-372b-4059-959a-ccb7e556f6be.png)

**Comment by jodemaey** [comment]
Hi,

I can try :-)

First can you tell me if you are trying to display the [online documentation](https://qgs.readthedocs.io/) or if you compiled the documentation on your computer and are trying to display the local version hence obtained?

**Comment by ifengfan** [comment]
> Hi,
> 
> I can try :-)
> 
> First can you tell me if you are trying to display the [online documentation](https://qgs.readthedocs.io/) or if you compiled the documentation on your computer and are trying to display the local version hence obtained?

Hi Jonathan,
I mean the online documentation. I've tried the Chrome and Safari browser on a Mac, and Chrome and Edge on Win 10. It all went the same as shown in the screenshot. But on an iOS Safari, the formulas look all right.

**Comment by jodemaey** [comment]
Ok good ! Nice to hear it is solved.
